import { notFound } from "next/navigation";
import { PageHeader } from "@/components/page-header";
import { Badge } from "@/components/ui/badge";
import { Card, CardTitle } from "@/components/ui/card";
import { requireAuth } from "@/lib/auth";
import { getCase } from "@/lib/data";
import { addCaseActivity, sendDemoSmsAction, sendDemoWhatsAppAction } from "@/lib/server-actions";
import { caseStageLabels, priorityLabels } from "@/lib/labels";
import { formatDate, formatMoney } from "@/lib/utils";

export default async function CaseDetailsPage({ params }: { params: Promise<{ id: string }> }) {
  const session = await requireAuth();
  const { id } = await params;
  const item = await getCase(session, id);
  if (!item) notFound();
  return <><PageHeader title={item.caseNumber} description={`${item.customer.companyName} | ${item.invoice?.invoiceNumber ?? "بدون فاتورة"}`} /><section className="grid gap-4 lg:grid-cols-4"><Card><p>المبلغ</p><p className="text-2xl font-extrabold">{formatMoney(item.outstandingAmount.toString())}</p></Card><Card><Badge>{caseStageLabels[item.stage]}</Badge></Card><Card><Badge tone="warning">{priorityLabels[item.priority]}</Badge></Card><Card><p>المتابعة</p><p>{formatDate(item.nextFollowUpDate)}</p></Card></section><section className="mt-6 grid gap-6 xl:grid-cols-[1fr_.9fr]"><Card><CardTitle>خط زمني للتواصل</CardTitle><div className="mt-4 grid gap-3">{item.activities.map((a) => <div key={a.id} className="rounded-md border border-border p-3"><p className="font-bold">{a.summary}</p><p className="text-sm text-muted-foreground">{a.user?.name ?? "-"} | {formatDate(a.createdAt)} | {a.outcome ?? "-"}</p></div>)}</div><form action={addCaseActivity} className="mt-4 grid gap-3"><input type="hidden" name="caseId" value={item.id} /><textarea name="summary" className="rounded-md border px-3 py-2" placeholder="ملخص النشاط" required /><input name="outcome" className="rounded-md border px-3 py-2" placeholder="النتيجة" /><input name="nextActionDate" type="date" className="rounded-md border px-3 py-2" /><select name="stage" className="rounded-md border px-3 py-2"><option value={item.stage}>الإبقاء على المرحلة</option><option value="CONTACTED">تم التواصل</option><option value="PROMISE_TO_PAY">وعد بالسداد</option><option value="ESCALATED">مصعدة</option><option value="CLOSED_PAID">مغلقة بسداد</option></select><button className="rounded-md bg-primary px-4 py-2 text-white">إضافة نشاط</button></form></Card><Card><CardTitle>إرسال رسالة</CardTitle><form action={sendDemoSmsAction} className="mt-4 grid gap-3"><input type="hidden" name="caseId" value={item.id} /><input type="hidden" name="customerId" value={item.customerId} /><input name="recipientPhone" defaultValue={item.customer.phone ?? ""} className="rounded-md border px-3 py-2" /><textarea name="messageBody" defaultValue="نذكركم بوجود مبلغ مستحق ونأمل السداد أو التواصل معنا." className="rounded-md border px-3 py-2" /><button className="rounded-md border border-border px-4 py-2 font-bold">إرسال SMS تجريبي</button></form><form action={sendDemoWhatsAppAction} className="mt-4 grid gap-3"><input type="hidden" name="caseId" value={item.id} /><input type="hidden" name="customerId" value={item.customerId} /><input name="recipientPhone" defaultValue={item.customer.whatsapp ?? ""} className="rounded-md border px-3 py-2" /><textarea name="messageBody" defaultValue="مرحباً، نتابع معكم الفاتورة المستحقة. شكراً لتعاونكم." className="rounded-md border px-3 py-2" /><button className="rounded-md bg-primary px-4 py-2 font-bold text-white">إرسال واتساب تجريبي</button></form></Card></section></>;
}
